# Generated by Django 4.1.3 on 2022-11-30 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=444, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tanlov',
            field=models.CharField(default=222, max_length=20),
            preserve_default=False,
        ),
    ]
