# Generated by Django 3.2 on 2022-12-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_toppost'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
